server:
  port: 8082

spring:
  application:
    name: packages-service

logging:
  level:
    com.parcial.packages: DEBUG
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
