server:
  port: 8081

spring:
  application:
    name: shipments-service

logging:
  level:
    com.parcial.shipments: DEBUG
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
